# origin: https://github.com/rustfs/rustfs/blob/76fa86fdc5d1e696508758ebe1a830be105ef8ad/docker-compose-simple.yml
services:

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.80
    container_name: rustfs-server
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "127.0.0.1:9000:9000" # S3 API Port
      - "127.0.0.1:9001:9001" # Console Port
    environment:
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_EXTERNAL_ADDRESS=:9000
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=rustfsadmin # CHANGEME
      - RUSTFS_SECRET_KEY=rustfsadmin # CHANGEME
      - RUSTFS_OBS_LOGGER_LEVEL=info
      - RUSTFS_TLS_PATH=/opt/tls
      # Object Cache
      - RUSTFS_OBJECT_CACHE_ENABLE=true
      - RUSTFS_OBJECT_CACHE_TTL_SECS=300
    volumes:
      - rustfs_data:/data/rustfs
      - logs_data:/app/logs
    networks:
      - rustfs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # RustFS volume permissions fixer service
  volume-permission-helper:
    image: alpine
    volumes:
      - rustfs_data:/data
      - logs_data:/logs
    command: ["sh", "-c", "chown -R 10001:10001 /data /logs && echo '[notice] volume permissions fixed' && exit 0"]
    restart: "no"

networks:
  rustfs:

volumes:
  rustfs_data:
  logs_data:
