version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/azurite"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/kafka"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/keycloak"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/mongo"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/nats"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/postgres"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/rabbitmq"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/redis"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/traefik"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
