services:

  traefik:
    image: traefik:3.6.7
    ports:
      - "127.0.0.1:4000:4000"
      - "127.0.0.1:6982:6982"
    networks:
      - traefik
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml

  frontend-mock:
    image: ealen/echo-server:0.9.2
    environment:
      APP_NAME: frontend mock
    networks:
      - traefik

  backend-mock:
    image: ealen/echo-server:0.9.2
    environment:
      APP_NAME: backend mock
    networks:
      - traefik

networks:
  traefik:
